migrate(
  (app) => {
    try {
      const natalyRecords = app.findRecordsByFilter(
        'funcionarios',
        "nome = 'Nataly Tayna Figueiredo da Silva'",
        '',
        1,
        0,
      )

      if (natalyRecords.length > 0) {
        const nataly = natalyRecords[0]
        const mayBalances = app.findRecordsByFilter(
          'saldos_mensais',
          `funcionario_id = '${nataly.id}' && mes = 5 && ano = 2026`,
          '',
          100,
          0,
        )

        for (const balance of mayBalances) {
          app.delete(balance)
        }
      }
    } catch (err) {
      console.log('Error deleting corrupted May 2026 balance for Nataly:', err)
    }
  },
  (app) => {
    // Down migration is a no-op as we are deleting a corrupted record
    // that will be automatically regenerated by the frontend application
    // upon the next visit to the employee's timecard.
  },
)
